replicaCount: 1

image:
  registry: "ghcr.io"
  repository: "bohdan99i/tbot"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.5-d4024bd"
   os: linux
  arch: amd64
secret:
  name: tbot
  tokenName: TELE_TOKEN
  tokenKey: token
  secretValue: TELE_TOKEN
securityContext:
  privileged: true

