name: TBOT-CICD

on:
  push:
    branches:
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME3 }}
          password: ${{ secrets.DOCKERHUB_TOKEN3 }}

      - name: Build&Push
        env:
          APP: "tbot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME3 }}
        run: make image push
